### ISSUE TITLE
Constants can be re-assigned?

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/ruby-variable-assignment#3]
User Pavling (https://learn.co/Pavling) reports:

The section about constants is wrong. They *can* be re-assigned - the message is a warning, not an error. Running the code in the example results in: ``` > CONSTANT => "I can't be reassigned!" ```

**Comment by SophieDeBenedetto** [comment]
is this an issue pertaining to this lab? I don't see a section about constants.

**Comment by markedwardmurray** [comment]
it's misapplied, the issue belongs on the next reading: https://github.com/learn-co-curriculum/ruby-variable-types-readme

**Comment by deniznida** [comment]
@SophieDeBenedetto @markedwardmurray Can we just close this issue if it's misapplied? Of course after opening an issue for the correct lab.
