### ISSUE TITLE
This seems redundant

### ISSUE THREAD

**Issue by patrickhsanders** [learn-co-curriculum/ruby-variable-assignment#66]
This seems redundant at this location because Learn has already been introduced and used many times. 

<em>However, if you get:

-bash: learn: command not found
Then you need to install Learn. Do that via: gem install learn-co in your command line.

To solve this test failure, create a local variable greeting in the variable.rb file. Set greeting equal to the string "Hello World". Run learn to see if you did this correctly.<em>

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  due 8/21
