### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by jcadamsjc** [learn-co-curriculum/ruby-variable-assignment#69]
Doing this correctly, submitted several times, but still a BUILD FAILURE. Keep getting no specs in file. Any ideas? I've since moved on but would like to see it correct. Thanks.

**Comment by AnnJohn** [comment]
@jcadamsjc sorry for the delay with this. For immediate help, please use the Ask a Question tool in Learn and someone from our Instructor support team will get back to you. You can also file a bug report. Thanks!
