### ISSUE TITLE
Fork and Pull Request are not updating

### ISSUE THREAD

**Issue by JoanBrownCS** [learn-co-curriculum/ruby-variable-assignment#70]
I am following the same procedures as for previous labs, but the Fork button on the Learn interface is not showing completion when I click on Git and Fork the lab.
I can still go to Nitrous and complete the lab, type "learn submit" when I am finished, and to back to learn and the Pull Request button on the right is not showing completion.

**Comment by AnnJohn** [comment]
@JoanBrownCS sorry for the delay with this. For all immediate help, please use the Ask a Question tool and someone from our instructor support team will help you out. Thanks!
