### ISSUE TITLE
LOCAL BUILD FAILURE

### ISSUE THREAD

**Issue by jcadamsjc** [learn-co-curriculum/ruby-variable-assignment#71]
Code is correct, yet getting a LOCAL BUILD FAILURE. I've moved way past this lesson, but still check now and then. Not resolved.

**Comment by AnnJohn** [comment]
Hi @jcadamsjc sorry for the issue. This is an engineering issue on our end, but for immediate help with this, you can use the Ask a Question tool in Learn and someone will get back to you on it. Thanks.
