### ISSUE TITLE
Can't open using nitrous

### ISSUE THREAD

**Issue by KinichAjaw** [learn-co-curriculum/ruby-variable-assignment#72]
Every time I've tried to open a lesson a popup appears telling me that nitrous can't load the lab. I've tried switching to local per troubleshooting but that hasn't worked, and I'm now unable to access the option to open in nitrous.

**Comment by AnnJohn** [comment]
hi @KinichAjaw sorry for the issue that you're having. We use this space for issues specifically related to the content in the lessons so might not always be able to respond quickly to the technical problems. 

Can you file a bug report? If you hover over your profile in Learn, you'll see an option there to file a bug report. Also you can use the Ask a Question tool to get an immediate response. Thanks!
