### ISSUE TITLE
Failures: This is the error messaging I received

### ISSUE THREAD

**Issue by hersrud** [learn-co-curriculum/ruby-variable-assignment#74]
When fixing the variable.rb file by defining the string "Hello World" using the variable greeting; the only error message that I received was as follows:

Failed examples:
rspec ./spec/variable_spec.rb:4 # ./variable.rb defined a local variable called greeting and set it equal to 'Hello World'

I was able to define the variable and correctly execute the file. 

The directions state when 1st executing the learn command the user should receive the following prompt:

Failures:
 
  1) ./variable.rb defined a local variable called greeting and set it equal to 'Hello World'
     Failure/Error: greeting = get_variable_from_file('./variable.rb', "greeting")
     NameError:
       local variable `greeting' not defined in ./variable.rb.
     # ./spec/spec_helper.rb:14:in `rescue in get_variable_from_file'
     # ./spec/spec_helper.rb:11:in `get_variable_from_file'
     # ./spec/variable_spec.rb:5:in `block (2 levels) in <top (required)>'

**Comment by AnnJohn** [comment]
hi @hersrud the error message in the instructions looks like the error message you received on your end.  The remainder of that issue in the instructions is the type of error that it was (NameError). If you didn't see that in your local version, don't worry too much about it. The main part of the error message still showed up and you were able to get it passing. Thanks
