### ISSUE TITLE
Enviorment is not updating

### ISSUE THREAD

**Issue by bbeason** [learn-co-curriculum/ruby-variable-assignment#76]
There is an issue with syncing between atom and the lesson. I have made the changes to the .rb files. When I run the test in command line the files show to have not been updated with what is in the text editor. I skipped past the lesson thinking that it was something that I was doing wrong. I have now clicked the open button on the lesson and the command line is showing the correct files but the tree is not showing the new lesson. I have used the pwd and ls command and they are both showing the files. But once again the file tree is not showing the new lesson.

**Comment by AnnJohn** [comment]
Hi @bbeason thanks for raising this. This is a technical issue (we use this space for issues specifically related to curriculum content) so can you please file a bug report instead? If you hover over your profile pic in Learn, you'll see a dropdown menu where one of the options is to file a bug report. 

Thanks!
