### ISSUE TITLE
Unable to fork this lab correctly

### ISSUE THREAD

**Issue by hafizrahman1** [learn-co-curriculum/ruby-variable-assignment#77]
In the terminal at the beginning, it showed all the files but not in the menu. I updated the Git hub and later on I got the following message when I click the open for forking the variable lab!
![variable_lab_forking_error](https://cloud.githubusercontent.com/assets/14155626/15654999/d6299528-2666-11e6-9fdc-66675b9e3296.jpg)

**Comment by AnnJohn** [comment]
hi @hafizrahman1 sorry for the issue that you're having. Since this is a technical problem which is most likely very specific to you, can you please use the Ask a Question tool and someone from our Learn Expert team will get back to you? Thanks.
