### ISSUE TITLE
Misspelled title on Curriculum drop-down menu

### ISSUE THREAD

**Issue by Josh-Stillman** [learn-co-curriculum/ruby-variable-assignment#80]
The title of this unit is misspelled on the Curriculum drop-down menu as "Varlable" instead of "Variable".

**Comment by gj** [comment]
Hi @Josh-Stillman !

It says `Variable`, with an `i`, so it's probably down to a combination of the font and the resolution of your screen. We're aware of the issue and are working towards a solution. Thanks for raising the issue!
