### ISSUE TITLE
Submit

### ISSUE THREAD

**Issue by Nasrin7** [learn-co-curriculum/ruby-variable-assignment#95]
I did my first lab. But my submit button is red, and I cannot go to next lesson!

**Comment by Nasrin7** [comment]
It worked! 👍

**Comment by lizbur10** [comment]
Hi there,

I'm glad you got this resolved!

In future, a good place to go for help with this type of issue is the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
